# Generated by Django 5.1.4 on 2025-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
