# Generated by Django 5.1.4 on 2025-01-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheckout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='street_address',
        ),
    ]
