# Generated by Django 5.1.4 on 2025-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheckout', '0002_rename_street_address1_order_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
