# Generated by Django 5.1.4 on 2025-01-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
