# Generated by Django 5.1.4 on 2025-01-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_color_color_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.color'),
        ),
    ]
