# Generated by Django 5.1.4 on 2025-02-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_color_products_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
